apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    url: postgres:5432
    database: postgres_db
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      sslmode: "disable"
    isDefault: true
    editable: true
